language: go
go:
  - 1.8
  - 1.9
service: docker
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - $GOPATH/bin/dep ensure
script:
  - docker-compose up -d
  - go test -v -covermode=count -coverprofile=tcb.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
