version: '3'
services:
  tcb_test_couch:
    container_name: "tcb_test_couch"
    image: deadcheat/couchbase:latest
    deploy:
      replicas: 1
    environment:
      BUCKET_NAME: "default"
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
