version: '3'

services:
  tcb_test_couch1:
    container_name: "tcb_test_couch1"
    image: deadcheat/couchbase:latest
    deploy:
      replicas: 1
    environment:
      BUCKET_NAME: "default"
      # BUCKET_PASSWORD: "test"
    ports:
      - 8091:8091
